### ISSUE TITLE
role fails when grub_consoles is empty

### ISSUE THREAD

**Issue by tedgin** [adfinis-sygroup/ansible-role-grub#10]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /home/tedgin/.ansible.cfg
  configured module search path = ['/home/tedgin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

DEFAULT_FORKS(/home/tedgin/.ansible.cfg) = 10
DEFAULT_TIMEOUT(/home/tedgin/.ansible.cfg) = 20
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/tedgin/.ansible_vault_pass.txt
INTERPRETER_PYTHON(/home/tedgin/.ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/tedgin/.ansible.cfg) = False

##### OS / ENVIRONMENT

The ansible control node is running CentOS 7.
The managed node is running Ubuntu 20.04.

##### SUMMARY

When there are no consoles for grub, the role fails complaining `grub_console` isn't defined. 

##### STEPS TO REPRODUCE

Set the role variable `grub_consoles` to `[]` in the playbook, and run it

```yaml
---
- name: Prepare for PostgreSQL
  hosts: dbms
  become: true
  roles:
     - role: adfinis_sygroup.grub
       grub_consoles: []
```

##### EXPECTED RESULTS

I expect it to update `/etc/default/grub`.

##### ACTUAL RESULTS

It fails to errors out before updating `/etc/default/grub`.

```
BECOME password: 

PLAY [Prepare for PostgreSQL] **********************************************************************

TASK [Gathering Facts] *****************************************************************************
ok: [qairods.cyverse.org]

TASK [adfinis_sygroup.grub : include os specific vars] *********************************************
ok: [qairods.cyverse.org] => (item=/home/tedgin/repos/ds/deployments/qa/playbooks/dbms/roles/adfinis_sygroup.grub/vars/Debian.yml)

TASK [adfinis_sygroup.grub : install grub related packages] ****************************************
ok: [qairods.cyverse.org]

TASK [adfinis_sygroup.grub : remove unused grub packages] ******************************************
ok: [qairods.cyverse.org]

TASK [adfinis_sygroup.grub : create the grub configuration] ****************************************
fatal: [qairods.cyverse.org]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'grub_console' is undefined"}

PLAY RECAP *****************************************************************************************
qairods.cyverse.org        : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by eyenx** [comment]
Looks like `grub_console` gets only set when `grub_consoles` is non-empty.

It gets used here to https://github.com/adfinis-sygroup/ansible-role-grub/blob/41ddf5795a63a856adb5037fdd030701e4aaf905/templates/etc/default/grub.j2#L25

**Comment by shurik-io** [comment]
Fixed it. Thank you for opening the very well described issue @tedgin. Details can be found in the PR.
